FROM ghcr.io/texas2010/texas2010-dockerfiles/texas2010-lib-setup-base:latest

ENV TEST_KIND=integration

WORKDIR /apps/base

COPY package.json package-lock.json ./
COPY rollup.dts.config.js vite.config.ts vitest.config.ts tsconfig.* ./
COPY config/ ./config/
COPY integration/ ./integration/
COPY src/ ./src/
COPY utils ./utils/

RUN npm ci
RUN npm run build

CMD ["sh", "./integration/scripts/docker-entrypoint.sh"]